name: Deploy Snipe-IT to Azure Web App

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, gd, pdo, pdo_mysql, zip
          tools: composer

      # Install dependencies
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # Generate optimized build (optional)
      - name: Prepare Laravel cache
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache || true

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: <YOUR-WEBAPP-NAME>
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
